[colors]
background = '#1d24198e'
black = '#1d2419'
blue = '#A6AD6F'
cursor = '#c6c8c5'
cyan = '#72A783'
foreground = '#c6c8c5'
green = '#D2B59B'
magenta = '#BAC38C'
red = '#C4C88C'
tabs = '#c6c8c5'
tabs-active = '#F0D1B2'
white = '#c6c8c5'
yellow = '#c6c8c5'
dim-black = '#1d24198e'
dim-blue = '#A6AD6F8e'
dim-cyan = '#72A7838e'
dim-foreground = '#c6c8c58e'
dim-green = '#D2B59B8e'
dim-magenta = '#BAC38C8e'
dim-red = '#C4C88C8e'
dim-white = '#F0D1B28e'
dim-yellow = '#c6c8c58e'
light-black = '#A6AD6F'
light-blue = '#72A783'
light-cyan = '#D2B59B'
light-foreground = '#BAC38C'
light-green = '#C4C88C'
light-magenta = '#F0D1B2'
light-red = '#c6c8c5'
light-white = '#A6AD6F'
light-yellow = '#72A783'
