# Shell variables
# Generated by 'wal'
wallpaper="/data/data/com.termux/files/home/Pictures/Wallpapers/wallpaper.jpg"

# Special
background='#1d2419'
foreground='#c6c8c5'
cursor='#c6c8c5'

# Colors
color0='#1d2419'
color1='#A6AD6F'
color2='#72A783'
color3='#D2B59B'
color4='#BAC38C'
color5='#C4C88C'
color6='#F0D1B2'
color7='#c6c8c5'
color8='#6a7761'
color9='#A6AD6F'
color10='#72A783'
color11='#D2B59B'
color12='#BAC38C'
color13='#C4C88C'
color14='#F0D1B2'
color15='#c6c8c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
