--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/data/data/com.termux/files/home/Pictures/Wallpapers/wallpaper.jpg"

-- Special
background="#1d2419"
foreground="#c6c8c5"
cursor="#c6c8c5"

-- Colors
color0="#1d2419"
color1="#A6AD6F"
color2="#72A783"
color3="#D2B59B"
color4="#BAC38C"
color5="#C4C88C"
color6="#F0D1B2"
color7="#c6c8c5"
color8="#6a7761"
color9="#A6AD6F"
color10="#72A783"
color11="#D2B59B"
color12="#BAC38C"
color13="#C4C88C"
color14="#F0D1B2"
color15="#c6c8c5"
