foreground         #c6c8c5
background         #1d2419
background_opacity 1.0
cursor             #c6c8c5

active_tab_foreground     #1d2419
active_tab_background     #c6c8c5
inactive_tab_foreground   #c6c8c5
inactive_tab_background   #1d2419

active_border_color   #c6c8c5
inactive_border_color #1d2419
bell_border_color     #A6AD6F

color0       #1d2419
color8       #6a7761
color1       #A6AD6F
color9       #A6AD6F
color2       #72A783
color10      #72A783
color3       #D2B59B
color11      #D2B59B
color4       #BAC38C
color12      #BAC38C
color5       #C4C88C
color13      #C4C88C
color6       #F0D1B2
color14      #F0D1B2
color7       #c6c8c5
color15      #c6c8c5
