# pywal theme for ghostty

background = 1d2419
foreground = c6c8c5
cursor-color = c6c8c5
selection-background = c6c8c5
selection-foreground = 1d2419

palette = 0=#1d2419
palette = 1=#A6AD6F
palette = 2=#72A783
palette = 3=#D2B59B
palette = 4=#BAC38C
palette = 5=#C4C88C
palette = 6=#F0D1B2
palette = 7=#c6c8c5
palette = 8=#6a7761
palette = 9=#A6AD6F
palette = 10=#72A783
palette = 11=#D2B59B
palette = 12=#BAC38C
palette = 13=#C4C88C
palette = 14=#F0D1B2
palette = 15=#c6c8c5
